<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\SiteSettingController;
use App\Http\Controllers\UserManagementController;



// Public Routes
// Route::get('/', function () {
//     return view('welcome');
// });


Route::middleware(['auth', 'verified'])->group(function () {
});

// Authenticated User Routes
Route::middleware(['auth', 'verified'])->group(function () {

    // Route::get('/welcome', function () {
    //     return view('welcome');
    // })->name('welcome');

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    // Profile Routes
    Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Authentication Routes (Generated by Laravel Breeze)
require __DIR__ . '/auth.php';

// Admin Panel Routes with Admin Middleware
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    // User Management Resource Routes
    Route::resource('user-management', UserManagementController::class)->names([
        'index' => 'user-management.index',
        'create' => 'user-management.create',
        'store' => 'user-management.store',
        'edit' => 'user-management.edit',
        'update' => 'user-management.update',
        'destroy' => 'user-management.destroy',
        ]);
    // Add the updateRoles route for updating user roles
    // Route::put('user-management/{user}/update-roles', 'UserManagementController@updateRoles')
    //     ->name('user-management.updateRoles');
    // Route::put('/admin/user-management/{user}', [UserManagementController::class, 'update'])->name('admin.user-management.update');




    // Admin Dashboard
    Route::get('/', [AdminController::class, 'index'])->name('index');

    // Site Setting Routes
    Route::prefix('sitesetting')->group(function () {
        Route::get('/', [SiteSettingController::class, 'index'])->name('sitesetting.index');
        Route::get('/edit/{id}', [SiteSettingController::class, 'edit'])->name('sitesetting.edit');
        Route::post('/update', [SiteSettingController::class, 'update'])->name('sitesetting.update');
        Route::get('/create', [SiteSettingController::class, 'create'])->name('sitesetting.create');
        Route::post('/store', [SiteSettingController::class, 'store'])->name('sitesetting.store');
    });

    // About Routes
    Route::prefix('about')->group(function () {
        Route::get('/', [AboutController::class, 'index'])->name('about.index');
        Route::get('/create', [AboutController::class, 'create'])->name('about.create');
        Route::post('/store', [AboutController::class, 'store'])->name('about.store');
        Route::get('/edit/{id}', [AboutController::class, 'edit'])->name('about.edit');
        Route::post('/update', [AboutController::class, 'update'])->name('about.update');
        Route::delete('/destroy/{id}', [AboutController::class, 'destroy'])->name('about.destroy');
    });

    // Category Routes
    Route::prefix('categories')->group(function () {
        Route::get('/create', [CategoryController::class, 'create'])->name('categories.create');
        Route::post('/', [CategoryController::class, 'store'])->name('categories.store');
        Route::get('/{category}/edit', [CategoryController::class, 'edit'])->name('categories.edit');
        Route::put('/{category}', [CategoryController::class, 'update'])->name('categories.update');
        Route::delete('/{category}', [CategoryController::class, 'destroy'])->name('categories.destroy');
        Route::get('/', [CategoryController::class, 'index'])->name('categories.index');
    });

    // Posts Routes
    Route::prefix('posts')->group(function () {
        Route::get('/', [PostsController::class, 'index'])->name('posts.index');
        Route::get('/create', [PostsController::class, 'create'])->name('posts.create');
        Route::post('/', [PostsController::class, 'store'])->name('posts.store');
        Route::get('/{post}/edit', [PostsController::class, 'edit'])->name('posts.edit');
        Route::put('/{post}', [PostsController::class, 'update'])->name('posts.update');
        Route::delete('/{post}', [PostsController::class, 'destroy'])->name('posts.destroy');
    });

    // Logout
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');


    // Route::get('/', [LandingPageController::class, 'index']);
});
